<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      lang="en">
                         
  
<!-- Mirrored from www.py.cz/UnboundLocalError/diff by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:01:58 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta http-equiv="Content-Type"
          content="text/html;charset=utf-8" />
    
    <link rel="stylesheet" type="text/css"
          href="../FrontPage/stylesheet.css" />
    <title>PyCZ: Programovací jazyk Python, aplikační servery a frameworky, atd. UnboundLocalError</title>
    
    
    <meta name="robots" content="noindex,nofollow" />
  
  
  </head>
  <body>
    
    <div>
      <div id="pageheaderall" class="pageheader">
      <div id="accesskeys">
      <a accesskey="0"
         href="http://www.py.cz/UnboundLocalError/helpaccesskeys"></a>
      <a accesskey="f" href="http://www.py.cz/FrontPage"></a>
      <a accesskey="c"
         href="http://www.py.cz/FrontPage/contents#UnboundLocalError"></a>
      <a accesskey="r"
         href="http://www.py.cz/FrontPage/recentchanges"></a>
      <a accesskey="" href="http://www.py.cz/FrontPage"></a>
      
      <a accesskey="i"
         href="http://www.py.cz/FrontPage/wikiindex"></a>
      
      <a accesskey="o"
         href="http://www.py.cz/FrontPage/useroptions?redirectURL=http%3A//www.py.cz/UnboundLocalError"></a>
      <a accesskey="h" href="http://www.py.cz/HelpPage"></a>
      
      
      <a accesskey="n"
         href="http://www.py.cz/UnicodeEncodeError"></a>
      <a accesskey="p" href="http://www.py.cz/TypeError"></a>
      <a accesskey="u" href="http://www.py.cz/ErrorsVyjimky"></a>
      <a accesskey="v"
         href="http://www.py.cz/UnboundLocalError"></a>
      <a accesskey="m"
         href="http://www.py.cz/UnboundLocalError/subscribeform"></a>
      <a accesskey="b"
         href="http://www.py.cz/UnboundLocalError/backlinks"></a>
      <a accesskey="d"
         href="http://www.py.cz/UnboundLocalError/diff"></a>
      <a accesskey="y"
         href="http://www.py.cz/UnboundLocalError/history"></a>
      <a accesskey="e"
         href="http://www.py.cz/UnboundLocalError/editform"></a>
      
    </div>
      <div id="navlinks" class="linkpanel">
      <table class="shade1" width="100%" border="0" cellspacing="0">
        <tr>
          <td align="right">
            
      <a href="http://www.py.cz/FrontPage"
         title="show front page">
      <span>home</span></a>
      <a href="http://www.py.cz/FrontPage/contents#UnboundLocalError"
         title="show wiki contents">
      <span>contents</span></a>
      <a href="http://www.py.cz/FrontPage/recentchanges"
         title="show wiki recent changes">
      <span>changes</span></a>
      
      <a title="show wiki index"
         href="http://www.py.cz/FrontPage/wikiindex">
      <span>index</span></a>
      
      <a title="show wiki options"
         href="http://www.py.cz/FrontPage/useroptions?redirectURL=http%3A//www.py.cz/UnboundLocalError">
      <span>options</span></a>
      <a title="show help page"
         href="http://www.py.cz/HelpPage">
      <span>help</span></a>
    
            
      
      <a href="http://www.py.cz/UnboundLocalError/subscribeform"
         title="configure email subscription to this page or site">
        
      <span>subscribe</span></a>
      
      <a href="http://www.py.cz/UnboundLocalError/editform"
         title="edit-page (last edited 9 years ago by geon)">
      <span>edit</span></a>
      
    
          </td>
        </tr>
      </table>
    </div>
      <div id="pageheader">
        <form method="GET"
              action="http://www.py.cz/FrontPage/searchwiki">
          <table width="100%" border="0" cellspacing="0">
            <tr>
              <!-- logo -->
              <td id="logo" width="1%" valign="top"
                  class="logo">
                
                  <a title="go to home page"
                     href="http://www.py.cz/FrontPage">
                    
                    <img src="http://www.py.cz/UnboundLocalError/logo.jpg" border="0" alt="home" />
                    
                  </a>
                  &nbsp;
                
              </td>
              <!-- page name and context (parent topics) -->
              <td align="left" width="79%">
                
                  <small><ul class="outline expandable">
 <li><a href="http://www.py.cz/PythonRoot" name="PythonRoot">PythonRoot</a>
<ul class="outline expandable">
  <li><a href="http://www.py.cz/ErrorsVyjimky" name="ErrorsVyjimky">ErrorsVyjimky</a>
<ul class="outline expandable">
  <li><h1 style="display:inline;"><a href="http://www.py.cz/UnboundLocalError/backlinks" title="which pages link to this one ?" name="UnboundLocalError">UnboundLocalError</a></h1></li>
</ul>
  </li>
</ul>
 </li>
</ul>
</small>
                
                
              </td>
              <!-- search form & page info -->
              <td class="searchbox" width="20%" align="right">
                
                  <input id="searchinput" class="formfield"
                         name="expr" type="text" size="20"
                         maxlength="100" value=""
                         title="search all pages" /><br />
                  <span class="lasteditor">last edited  <a href="http://www.py.cz/UnboundLocalError/history" title="show last edit" >9 years</a> ago by <b>geon</b></span><br>
                  <span class="creator">created 2006-03-01</span>   
                
                
              </td>
            </tr>
          </table>
        </form>
      </div>
      <div id="ratingform" align="right">  
      <!-- page rating form -->
      <div>
        <a name="ratingform"></a>
        <style type="text/css">
          input.rating {border:none;}
        </style>
        <form method="POST" id="ratingform"
              action="http://www.py.cz/UnboundLocalError/vote">
           <input type="image" name="vote0" value="0"
                  alt="0" class="rating" width="14"
                  height="13"
                  src="http://www.py.cz/p_/sp"
                  style=""
                  title="click to vote 0 (poor) for this page (0 votes)" /><input
    type="image" name="vote1" value="1" alt="1"
    class="rating" src="http://www.py.cz/UnboundLocalError/misc_/ZWiki/star_icon" style=""
    title="click to vote 1 (average) for this page (0 votes)" /><input
    type="image" name="vote2" value="2" alt="2"
    class="rating" src="http://www.py.cz/UnboundLocalError/misc_/ZWiki/blank_star_icon"
    style=""
    title="click to vote 2 (above average) for this page (0 votes)" /><input
    type="image" name="vote3" value="3" alt="3"
    class="rating" src="http://www.py.cz/UnboundLocalError/misc_/ZWiki/blank_star_icon"
    style=""
    title="click to vote 3 (good) for this page (0 votes)" /><input
    type="image" name="vote4" value="4" alt="4"
    class="rating" src="http://www.py.cz/UnboundLocalError/misc_/ZWiki/blank_star_icon"
    style=""
    title="click to vote 4 (great) for this page (0 votes)" /><input
    type="image" name="vote5" value="5" alt="5"
    class="rating" src="http://www.py.cz/UnboundLocalError/misc_/ZWiki/blank_star_icon"
    style=""
    title="click to vote 5 (superb) for this page (0 votes)" />
        </form>
      </div>
    </div>
    </div>
      <h1>Edit detail for UnboundLocalError revision 1 of 1</h1>
      <div class="formcontent">
        <table border="0" cellspacing="0" width="100%">
          <tr valign="top">

            <td align="left">
              <form style="display:inline"
                    action="http://www.py.cz/UnboundLocalError">
                <input type="submit" name="history:method"
                       value="Return to edit history" />
                
              </form>
            </td>

            <td align="center">
              <form style="display:inline"
                    action="http://www.py.cz/UnboundLocalError/diff">
                <input type="hidden" name="rev" />
                
                <input disabled="1" value=" &lt; "
                       type="submit" accesskey="," />
              </form>
              <a style="font-weight:bold"
                 href="http://www.py.cz/UnboundLocalError/diff?rev=1">1</a>
              <form style="display:inline"
                    action="http://www.py.cz/UnboundLocalError/diff">
                <input type="hidden" name="rev" />
                
                <input disabled="1" value=" &gt; "
                       type="submit" accesskey="." />
              </form>
            </td>

            <td align="right">
              <form style="display:inline"
                    action="http://www.py.cz/UnboundLocalError">
                <input type="hidden" name="rev" value="1" />
                <input value="Revert to this version"
                       type="submit" name="revert:method"
                       disabled="disabled" />
              </form>
            </td>

          </tr>
          <tr valign="top">
            <td colspan="3">
              <span>Editor:</span> geon
              <br />
              <span>Time:</span> 2006/05/25 15:57:28 GMT+0
            </td>
          </tr>
          <tr valign="top">
            <td colspan="3">
              <span>Note:</span> <span
    style="font-weight:bold; font-style:italic;">oprava chyb</span>
            </td>
          </tr>
        </table>
        <hr />
        <pre>
<b>changed:</b><span style="color:red;text-decoration:line-through">
-</span><span style="color:green">
Vysvětlení

 Pokud ve funkci použiji proměnnou a nesnažím
se do ní přiřazovat, jde o takzvanou volnou proměnnou
(free variable). Volnou se nazývá proto, protože
v bloku kódu neexistuje pevná vazba mezi jménem
'x' a konkrétním místem, kde je hodnota uložena.
V okamžiku odkazu se teprve poloha &quot;ve vyšších patrech&quot;
bude zjišťovat.

Pokud do proměnné něco přiřadím, stává se lokální 
proměnnou v daném bloku kódu. Vytváří se pevná
vazba z mého lokálního prostoru. Už nemůžeme hovořit
o volné proměnné (tj. o proměnné definované někde
ve vyšších patrech). Pevná vazba na lokální prostor
se vytváří i tehdy, když se do této proměnné
přiřazuje až později (ve stejném bloku), než když 
se z ní čte. Příklad::

    # soubor a.py 
    
    x = 10
    
    def funkce1():
        print x
    
    def funkce2():
        return x
    
    print x            # (1)
    funkce1()          # (2)
    print funkce2()    # (3)

Příkaz &quot;print x&quot; na řádku (1) vytiskne
podle očekávání hodnotu 10. Jde o proměnnou
definovanou na stejné úrovni.

Na řádku (2) voláme funkce1() a ta se
v příkazu &quot;print x&quot; tiskne proměnou, která
je definována na &quot;vyšší úrovni&quot;. Jde ale
o volnou proměnnou, která se postupně hledá
v nadřízených lokálních prostorech (zde
žádné nemáme) a nakonec v prostoru globálním.

Na řádku (3) tiskneme výsledek, který získáváme
voláním funkce2(). V jejím těle se pouze vrací
hodnota volné proměnné x. Jde o podobný případ,
jako u funkce1(). Hodnota proměnné x se pouze
zpracuje jiným způsobem.

Zkuste ale tohle::

    # soubor c.py 
    
    x = 10
    
    def funkce3():
        x = x + 1
        print x
    
    funkce3()

Při pokusu o spuštění se ukáže toto...::

    C:\tmp&gt;python c.py
    Traceback (most recent call last):
      File &quot;c.py&quot;, line 7, in ?
        funkce3()
      File &quot;c.py&quot;, line 4, in funkce3
        x = x + 1
    UnboundLocalError: local variable 'x' referenced before assignment

Jak už bylo uvedeno výše, přiřazení &quot;x = x + 1&quot; 
způsobí, že funkce3 už o proměnné x chce uvažovat
jako o lokální proměnné. Jenže tato lokální proměnná
je použita na pravé straně přiřazení a zatím jí
nebyla přiřazena žádná hodnota, tj. &quot;proveden
odkaz na lokální proměnnou 'x', které dosud nebylo 
nic přiřazeno&quot;. Ona vlastně proměnná x zatím 
neexistuje a chceme ji vytvořit a přiřadit
jí její neexistující hodnotu zvětšenou o jedničku.

Ve stejném bloku kódu označuje jedno jméno
jen jednu proměnnou. Python nedovolí, abychom
se na tuto proměnnou dívali chvíli jako na volnou
proměnnou (vytvořenou ve vyšších patrech) a o něco
později jako na lokální proměnnou. Z tohoto důvodu
selže i následující příklad::

    # soubor d.py 
    
    x = 10
    
    def funkce4():
        print x
        x = x + 1
    
    funkce4()

Po spuštění dostáváme:: 

    C:\tmp\a&gt;python d.py
    Traceback (most recent call last):
      File &quot;d.py&quot;, line 7, in ?
        funkce4()
      File &quot;d.py&quot;, line 4, in funkce4
        print x
    UnboundLocalError: local variable 'x' referenced before assignment

Tentokrát selže už příkaz &quot;print x&quot;, který
ve funkce1() normálně fungoval. Tehdy jsme se
ale na x dívali jako na volnou proměnnou 
(definovanou jinde). Jenže příkaz &quot;x = x + 1&quot;
ve funkce4() způsobí, že x nemůže být volnou
proměnnou. V okamžiku definice funkce4() už se
rozhodne o tom, že x bude lokální proměnná
a nikdy jinak. Za těchto okolností se na příkaz
&quot;print x&quot; pohlíží jako na pokus zobrazit obsah
dosud neexistující proměnné.

Pokud by Python nebyl tak přísný a měnil
by charakter proměnné z volné na lokální
až podle potřeby, mohlo by to fungovat, 
ale pro člověka by se zdrojový text stával
nepřehledným a v komplikovanějších případech 
by to mohlo vést k těžko odhalitelným chybám. 
Už jen v případě &quot;x = x + 1&quot; bychom vlastně
nemohli říci, co ten příkaz dělá, protože
bychom neměli jistotu, že se na obou stranách
přiřazení pracuje se stejnou proměnnou x.


Možná řešení

 Jako mustr si vemme::

    # soubor c.py 

    x = 10
    
    def funkce3():
        x = x + 1
        print x
    
    funkce3()    




 Důsledná lokalizace

  To je asi nejméně častý případ. Proměnná x má být ve funkci lokální a po opuštění funkce zaniká (tam venku ji nepotřebujeme). V tomto případě je to obzvláště nesmyslné, ale někdy to tak může být myšleno::

    def funkce3():
        x=10
        x = x + 1
        print x

 Oškivá globalizace

  Globalizováním proměnné x ve funkci ji spojíme s proměnnou x definovanou v hlavní části programu. Je to ale nečisté a nedoporučované řešení::

    def funkce3():
        global x
        x = x + 1
        print x

 Předáváním a vracením proměnné

  Proměnnou pokaždé do funkce předáme a na konci ji zase vrátíme::

    x = 10
    
    def funkce3(x):
        x = x + 1
        print x
        return x
    
    x = funkce3(x) 

 Použitím měnitelných typů

  Seznamy, třídy a další se mohou v těchto případěch uplatnit jako nosiče proměnných, které se dají měnit všude::

    x = [10]
    
    def funkce3():
        x[0] = x[0] + 1
        print x[0]
    
    funkce3()   </span>
</pre>
        <hr />
        <div><h2>Vysvětlení</h2>
<p> Pokud ve funkci použiji proměnnou a nesnažím
se do ní přiřazovat, jde o takzvanou volnou proměnnou
(free variable). Volnou se nazývá proto, protože
v bloku kódu neexistuje pevná vazba mezi jménem
<code>x</code> a konkrétním místem, kde je hodnota uložena.
V okamžiku odkazu se teprve poloha "ve vyšších patrech"
bude zjišťovat.</p>
<p>Pokud do proměnné něco přiřadím, stává se lokální 
proměnnou v daném bloku kódu. Vytváří se pevná
vazba z mého lokálního prostoru. Už nemůžeme hovořit
o volné proměnné (tj. o proměnné definované někde
ve vyšších patrech). Pevná vazba na lokální prostor
se vytváří i tehdy, když se do této proměnné
přiřazuje až později (ve stejném bloku), než když 
se z ní čte. Příklad:</p>

<pre>
    # soubor a.py 

    x = 10

    def funkce1():
        print x

    def funkce2():
        return x

    print x            # (1)
    funkce1()          # (2)
    print funkce2()    # (3)
</pre>
<p>Příkaz "print x" na řádku (1) vytiskne
podle očekávání hodnotu 10. Jde o proměnnou
definovanou na stejné úrovni.</p>
<p>Na řádku (2) voláme funkce1() a ta se
v příkazu "print x" tiskne proměnou, která
je definována na "vyšší úrovni". Jde ale
o volnou proměnnou, která se postupně hledá
v nadřízených lokálních prostorech (zde
žádné nemáme) a nakonec v prostoru globálním.</p>
<p>Na řádku (3) tiskneme výsledek, který získáváme
voláním funkce2(). V jejím těle se pouze vrací
hodnota volné proměnné x. Jde o podobný případ,
jako u funkce1(). Hodnota proměnné x se pouze
zpracuje jiným způsobem.</p>
<p>Zkuste ale tohle:</p>

<pre>
    # soubor c.py 

    x = 10

    def funkce3():
        x = x + 1
        print x

    funkce3()
</pre>
<p>Při pokusu o spuštění se ukáže toto...:</p>

<pre>
    C:\tmp&gt;python c.py
    Traceback (most recent call last):
      File "c.py", line 7, in ?
        funkce3()
      File "c.py", line 4, in funkce3
        x = x + 1
    UnboundLocalError: local variable 'x' referenced before assignment
</pre>
<p>Jak už bylo uvedeno výše, přiřazení "x = x + 1" 
způsobí, že funkce3 už o proměnné x chce uvažovat
jako o lokální proměnné. Jenže tato lokální proměnná
je použita na pravé straně přiřazení a zatím jí
nebyla přiřazena žádná hodnota, tj. "proveden
odkaz na lokální proměnnou <code>x</code>, které dosud nebylo 
nic přiřazeno". Ona vlastně proměnná x zatím 
neexistuje a chceme ji vytvořit a přiřadit
jí její neexistující hodnotu zvětšenou o jedničku.</p>
<p>Ve stejném bloku kódu označuje jedno jméno
jen jednu proměnnou. Python nedovolí, abychom
se na tuto proměnnou dívali chvíli jako na volnou
proměnnou (vytvořenou ve vyšších patrech) a o něco
později jako na lokální proměnnou. Z tohoto důvodu
selže i následující příklad:</p>

<pre>
    # soubor d.py 

    x = 10

    def funkce4():
        print x
        x = x + 1

    funkce4()
</pre>
<p>Po spuštění dostáváme:</p>

<pre>
    C:\tmp\a&gt;python d.py
    Traceback (most recent call last):
      File "d.py", line 7, in ?
        funkce4()
      File "d.py", line 4, in funkce4
        print x
    UnboundLocalError: local variable 'x' referenced before assignment
</pre>
<p>Tentokrát selže už příkaz "print x", který
ve funkce1() normálně fungoval. Tehdy jsme se
ale na x dívali jako na volnou proměnnou 
(definovanou jinde). Jenže příkaz "x = x + 1"
ve funkce4() způsobí, že x nemůže být volnou
proměnnou. V okamžiku definice funkce4() už se
rozhodne o tom, že x bude lokální proměnná
a nikdy jinak. Za těchto okolností se na příkaz
"print x" pohlíží jako na pokus zobrazit obsah
dosud neexistující proměnné.</p>
<p>Pokud by Python nebyl tak přísný a měnil
by charakter proměnné z volné na lokální
až podle potřeby, mohlo by to fungovat, 
ale pro člověka by se zdrojový text stával
nepřehledným a v komplikovanějších případech 
by to mohlo vést k těžko odhalitelným chybám. 
Už jen v případě "x = x + 1" bychom vlastně
nemohli říci, co ten příkaz dělá, protože
bychom neměli jistotu, že se na obou stranách
přiřazení pracuje se stejnou proměnnou x.</p>
<h2>Možná řešení</h2>
<p> Jako mustr si vemme:</p>

<pre>
    # soubor c.py 

    x = 10

    def funkce3():
        x = x + 1
        print x

    funkce3()    
</pre>
<h3> Důsledná lokalizace</h3>
<p>  To je asi nejméně častý případ. Proměnná x má být ve funkci lokální a po opuštění funkce zaniká (tam venku ji nepotřebujeme). V tomto případě je to obzvláště nesmyslné, ale někdy to tak může být myšleno:</p>

<pre>
    def funkce3():
        x=10
        x = x + 1
        print x
</pre>
<h3> Oškivá globalizace</h3>
<p>  Globalizováním proměnné x ve funkci ji spojíme s proměnnou x definovanou v hlavní části programu. Je to ale nečisté a nedoporučované řešení:</p>

<pre>
    def funkce3():
        global x
        x = x + 1
        print x
</pre>
<h3> Předáváním a vracením proměnné</h3>
<p>  Proměnnou pokaždé do funkce předáme a na konci ji zase vrátíme:</p>

<pre>
    x = 10

    def funkce3(x):
        x = x + 1
        print x
        return x

    x = funkce3(x) 
</pre>
<h3> Použitím měnitelných typů</h3>
<p>  Seznamy, třídy a další se mohou v těchto případěch uplatnit jako nosiče proměnných, které se dají měnit všude:</p>

<pre>
    x = [10]

    def funkce3():
        x[0] = x[0] + 1
        print x[0]

    funkce3()   
</pre>
<p>
</p>
</div>
      </div>
    </div>
    
  </body>

<!-- Mirrored from www.py.cz/UnboundLocalError/diff by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:01:58 GMT -->
</html>

