<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 
<!-- Mirrored from www.py.cz/pipermail/python/2006-February/004113.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:25:55 GMT -->
<HEAD>
   <TITLE> [python] IOError (111,
	'Connection refused') pri urllib.urlretrieve
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:python%40py.cz?Subject=%5Bpython%5D%20IOError%20%28111%2C%0A%09%27Connection%20refused%27%29%20pri%20urllib.urlretrieve&In-Reply-To=op.s5f4nd1g2xehyp%40localhost.localdomain">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=iso-8859-2">
   <LINK REL="Previous"  HREF="http://www.py.cz/pipermail/python/2006-February/004112.html">
   <LINK REL="Next"  HREF="http://www.py.cz/pipermail/python/2006-February/004109.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve</H1>
    <B>Michal Molhanec</B> 
    <A HREF="mailto:python%40py.cz?Subject=%5Bpython%5D%20IOError%20%28111%2C%0A%09%27Connection%20refused%27%29%20pri%20urllib.urlretrieve&In-Reply-To=op.s5f4nd1g2xehyp%40localhost.localdomain"
       TITLE="[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve">molhanec na seznam.cz
       </A><BR>
    <I>Ètvrtek Únor 23 23:21:58 CET 2006</I>
    <P><UL>
        <LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004112.html">[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve
</A></li>
        <LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004109.html">[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve: OPRAVA
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2006-February/date.html#4113">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/thread.html#4113">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/subject.html#4113">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/author.html#4113">[ autora ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>.: smilelover :. napsal(a):
&gt;<i> tak lynx spusteny na tom srv pres SSH se nepripoji prakticky nikam, ani 
</I>&gt;<i> na tu adresu, ani treba na Centrum.cz. Stejne tak wget.
</I>&gt;<i> Ze by to SF zakazoval schvalne?
</I>
ty nectes na SF dokumentaci?
viz 
<A HREF="http://sourceforge.net/docman/display_doc.php?docid=4297&amp;group_id=1#connectivity">http://sourceforge.net/docman/display_doc.php?docid=4297&amp;group_id=1#connectivity</A>


Outbound Connectivity

Project web servers: Outbound access to other hosts from the project web 
servers is strictly prohibited, and is blocked by firewall rules. This 
includes access to other SourceForge.net hosts; the only exception to 
this policy is access to our our project database servers. This 
restriction has been caused by past abuse. CVS and Subversion server 
access is not available from the project web servers. Any content needed 
from other SourceForge.net hosts should be retrieved and stored as a 
file or database entry that may then be accessed from scripts on the 
project web servers.

Project shell server: Access is not blocked to other SourceForge.net 
hosts from the project shell server. Access is blocked to hosts outside 
of SourceForge.net from the project shell server. This policy has been 
established as result of past service abuse. All content must be pushed 
to the shell server from an external host, rather than being pulled from 
the project shell servers.

Project database server: No outbound access is permitted from the 
project database servers (which cannot be accessed interactively by 
developers).

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004112.html">[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve
</A></li>
	<LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004109.html">[python] IOError (111,
	'Connection refused') pri urllib.urlretrieve: OPRAVA
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2006-February/date.html#4113">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/thread.html#4113">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/subject.html#4113">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/author.html#4113">[ autora ]</a>
         </LI>
       </UL>
<hr>
<a href="http://www.py.cz/mailman/listinfo/python">Dal¹í informace o konferenci Python</a><br>
</body>
<!-- Mirrored from www.py.cz/pipermail/python/2006-February/004113.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:25:55 GMT -->
</html>
