<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 
<!-- Mirrored from www.py.cz/pipermail/python/2006-February/004107.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:25:55 GMT -->
<HEAD>
   <TITLE> [python] IOError (111, 'Connection refused') pri urllib.urlretrieve
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:python%40py.cz?Subject=%5Bpython%5D%20IOError%20%28111%2C%20%27Connection%20refused%27%29%20pri%20urllib.urlretrieve&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=iso-8859-2">
   <LINK REL="Previous"  HREF="http://www.py.cz/pipermail/python/2006-February/004104.html">
   <LINK REL="Next"  HREF="http://www.py.cz/pipermail/python/2006-February/004108.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[python] IOError (111, 'Connection refused') pri urllib.urlretrieve</H1>
    <B>.: smilelover :.</B> 
    <A HREF="mailto:python%40py.cz?Subject=%5Bpython%5D%20IOError%20%28111%2C%20%27Connection%20refused%27%29%20pri%20urllib.urlretrieve&In-Reply-To="
       TITLE="[python] IOError (111, 'Connection refused') pri urllib.urlretrieve">smilelover na centrum.cz
       </A><BR>
    <I>Ètvrtek Únor 23 22:04:19 CET 2006</I>
    <P><UL>
        <LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004104.html">[python] Zajimavost
</A></li>
        <LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004108.html">[python] IOError (111, 'Connection refused') pri
	urllib.urlretrieve
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2006-February/date.html#4107">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/thread.html#4107">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/subject.html#4107">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/author.html#4107">[ autora ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Zdravim,
mam Python CGI skript, ktery za pomoci funkce urllib.urlretrieve stahne  
stranku. Konkretne ten kousek vypada takto:

self.tmpString =  
urllib.urlopen(&quot;<A HREF="http://dictionary.cambridge.org/results.asp?searchword=%s%22">http://dictionary.cambridge.org/results.asp?searchword=%s&quot;</A>  
% urllib.quote(query)).read()

Kdyz pouztim skript u sebe na localhostu, jede OK, ale kdyz ho nahraju na  
server (konkretne na SourceForge.net, ale stalo se mi to i jinde), dostanu  
IOError.
SSHcknul jsem se tam a zkusil to, vypada to takhle:

Python 2.3.3 (#1, May  7 2004, 10:31:40)
[GCC 3.3.3 20040412 (Red Hat Linux 3.3.3-7)] on linux2
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt;<i> import urllib
</I>&gt;&gt;&gt;<i> print  
</I>&gt;&gt;&gt;<i> urllib.urlopen(&quot;<A HREF="http://dictionary.cambridge.org/results.asp?searchword=evolution%22">http://dictionary.cambridge.org/results.asp?searchword=evolution&quot;</A>).read()
</I>Traceback (most recent call last):
   File &quot;&lt;stdin&gt;&quot;, line 1, in ?
   File &quot;/usr/lib/python2.3/urllib.py&quot;, line 76, in urlopen
     return opener.open(url)
   File &quot;/usr/lib/python2.3/urllib.py&quot;, line 181, in open
     return getattr(self, name)(url)
   File &quot;/usr/lib/python2.3/urllib.py&quot;, line 297, in open_http
     h.endheaders()
   File &quot;/usr/lib/python2.3/httplib.py&quot;, line 712, in endheaders
     self._send_output()
   File &quot;/usr/lib/python2.3/httplib.py&quot;, line 597, in _send_output
     self.send(msg)
   File &quot;/usr/lib/python2.3/httplib.py&quot;, line 564, in send
     self.connect()
   File &quot;/usr/lib/python2.3/httplib.py&quot;, line 548, in connect
     raise socket.error, msg
IOError: [Errno socket error] (111, 'Connection refused')

Musi to ten server nejak povolit nebo tak?
Dik

Dan

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004104.html">[python] Zajimavost
</A></li>
	<LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2006-February/004108.html">[python] IOError (111, 'Connection refused') pri
	urllib.urlretrieve
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2006-February/date.html#4107">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/thread.html#4107">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/subject.html#4107">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2006-February/author.html#4107">[ autora ]</a>
         </LI>
       </UL>
<hr>
<a href="http://www.py.cz/mailman/listinfo/python">Dal¹í informace o konferenci Python</a><br>
</body>
<!-- Mirrored from www.py.cz/pipermail/python/2006-February/004107.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:25:55 GMT -->
</html>
